/* BIGLWA Studio -> Collective Feed
 * Every upload starts as a private Firestore draft. The member explicitly posts it from Feed.
 */
const FIREBASE_CONFIG={apiKey:"AIzaSyAPUT8_pLNxdh5tbGpAmXBJiID3jVcA9DY",authDomain:"biglwa.firebaseapp.com",projectId:"biglwa",appId:"1:83232670555:web:e04927b20458390b3b507e"};
const WORKER="https://biglwa-instagram-api.leianmulatre-284.workers.dev";
let refs;
async function firebase(){if(!refs){const [{initializeApp,getApps},store,{getAuth}]=await Promise.all([import("https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js"),import("https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js"),import("https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js")]);const app=getApps()[0]||initializeApp(FIREBASE_CONFIG);refs={auth:getAuth(app),db:store.getFirestore(app),doc:store.doc,setDoc:store.setDoc,serverTimestamp:store.serverTimestamp};}return refs}
const clean=v=>String(v==null?"":v).trim();
async function uploadBlob(blob){if(!(blob instanceof Blob)||!blob.size)throw new Error("Choose or capture an image first.");const {auth}=await firebase(),user=auth.currentUser;if(!user)throw new Error("Sign in before uploading to the collective feed.");const token=await user.getIdToken();const type=clean(blob.type)||"image/jpeg";const res=await fetch(WORKER+"/media/feed-image",{method:"POST",headers:{"Authorization":"Bearer "+token,"Content-Type":type,"Content-Length":String(blob.size)},body:blob});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"The image could not be uploaded.");return data}
async function createStudioDraft({source,title,caption,blob,sourceUrl}={}){const {auth,db,doc,setDoc,serverTimestamp}=await firebase();const user=auth.currentUser;if(!user)throw new Error("Sign in to upload to the collective feed.");const identity=window.__biglwaIdentity||{};let imageUrl="",imageKey=null;if(blob) {const uploaded=await uploadBlob(blob);imageUrl=uploaded.url||"";imageKey=uploaded.key||null;}const id="studio_"+crypto.randomUUID().replace(/-/g,"");const data={uid:user.uid,username:clean(identity.username),authorName:clean(identity.name||identity.username||user.displayName||""),caption:clean(caption).slice(0,1000),imageUrl:imageUrl||null,imageKey:imageKey||null,imageUrls:imageUrl?[imageUrl]:[],imageKeys:imageKey?[imageKey]:[],source:clean(source||"studio").toLowerCase(),sourcePostId:id,sourceUrl:clean(sourceUrl)||null,mediaType:imageUrl?"IMAGE":"TEXT",orbitImported:false,studioImported:true,state:"draft",createdAt:serverTimestamp(),updatedAt:serverTimestamp()};await setDoc(doc(db,"posts",id),data);await setDoc(doc(db,"users",user.uid,"posts",id),data);return {id,...data}}
window.__biglwaCollectivePublish={createStudioDraft,uploadBlob};
