(() => {
  if (window.__biglwaModulePagesReadyV3) return;
  window.__biglwaModulePagesReadyV3 = true;

  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const main = $('.main');
  if (!main) return;

  const style = document.createElement('style');
  style.id = 'biglwa-module-pages-style-v3';
  style.textContent = `
    .module-workspace[hidden]{display:none!important}
    .main.module-view>.hero,.main.module-view>.masonry,.main.module-view>.site-policy-footer{display:none!important}
    .module-workspace{position:relative;z-index:4;min-height:calc(100vh - 66px);padding:34px clamp(18px,4vw,54px) 110px;background:linear-gradient(180deg,rgba(246,240,233,.94),rgba(239,231,223,.97));color:#272321}
    .module-shell{max-width:1160px;margin:0 auto}
    .module-top{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:26px}
    .module-back{border:1px solid #d8cec5;background:rgba(255,255,255,.68);border-radius:999px;padding:9px 14px;font:600 11px/1 system-ui;letter-spacing:.02em;color:#3a3430;cursor:pointer}
    .module-back:hover{background:#fff}
    .module-route{font-size:9px;letter-spacing:.14em;text-transform:uppercase;color:#8b8179}
    .module-heading{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:20px;align-items:end;padding-bottom:22px;border-bottom:1px solid #d9d0c8}
    .module-heading h1{margin:0;font:500 clamp(34px,6vw,66px)/.95 Georgia,serif;letter-spacing:-.04em}
    .module-heading p{max-width:700px;margin:12px 0 0;font-size:13px;line-height:1.6;color:#6e655f}
    .module-badge{align-self:start;border:1px solid #d8cec5;border-radius:999px;padding:8px 11px;font-size:9px;letter-spacing:.1em;text-transform:uppercase;background:rgba(255,255,255,.56);color:#746a64}
    .module-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(250px,.75fr);gap:14px;margin-top:20px}
    .module-card{border:1px solid #ddd3ca;background:rgba(255,255,255,.58);border-radius:18px;padding:18px;box-shadow:0 10px 30px rgba(55,42,34,.05)}
    .module-card.wide{grid-column:1/-1}.module-card h2{font:600 18px/1.1 Georgia,serif;margin:0 0 6px}.module-card>p{margin:0 0 14px;font-size:11px;line-height:1.55;color:#766c66}
    .module-form{display:grid;gap:8px}.module-form.two{grid-template-columns:1fr 1fr}.module-form.three{grid-template-columns:1.3fr 1fr .8fr}
    .module-input,.module-textarea,.module-select{width:100%;min-width:0;box-sizing:border-box;border:1px solid #d8cec5;background:rgba(255,255,255,.76);border-radius:11px;padding:10px 11px;font:11px/1.35 system-ui;color:#302b28;outline:none}
    .module-textarea{min-height:230px;resize:vertical;line-height:1.65}
    .module-input:focus,.module-textarea:focus,.module-select:focus{border-color:rgba(var(--aura-rgb,216,95,109),.7);box-shadow:0 0 0 3px rgba(var(--aura-rgb,216,95,109),.10)}
    .module-action{border:0;border-radius:11px;background:rgb(var(--aura-rgb,216,95,109));color:var(--aura-button-ink,#fff);padding:10px 13px;font:700 10px/1 system-ui;cursor:pointer}
    .module-action:disabled{opacity:.45;cursor:not-allowed}.module-action.secondary{background:#2a2725;color:#fff}.module-action.ghost{background:rgba(255,255,255,.65);color:#4f4742;border:1px solid #d8cec5}
    .module-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}
    .module-list{display:grid;gap:8px;margin-top:12px}.module-list-item{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;border:1px solid #dfd6cd;background:rgba(255,255,255,.5);border-radius:13px;padding:11px 12px}.module-list-item b,.module-list-item small{display:block}.module-list-item b{font-size:11px}.module-list-item small{font-size:9px;color:#857b74;margin-top:3px}.module-list-item button{border:0;background:transparent;color:#8b7e76;font-size:10px;cursor:pointer}
    .module-status{min-height:16px;margin-top:7px;font-size:9px;color:#81766f}.module-status.ok{color:#477650}
    .module-orbit{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.module-orbit-row{border:1px solid #ddd3ca;background:rgba(255,255,255,.52);border-radius:14px;padding:11px}.module-orbit-row header{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px}.module-orbit-row header b{font-size:11px}.module-orbit-row header span{min-width:28px;height:26px;padding:0 7px;border-radius:999px;display:grid;place-items:center;background:#292523;color:#fff;font-size:8px;font-weight:800}
    .orbit-field-label{display:block;font:700 8px/1.2 system-ui;letter-spacing:.08em;text-transform:uppercase;color:#8b8179;margin:8px 0 4px}
    .module-launchers{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.module-launcher{border:1px solid #ddd3ca;background:rgba(255,255,255,.58);border-radius:14px;padding:15px 12px;text-align:left;cursor:pointer}.module-launcher b{display:block;font-family:Georgia,serif;font-size:14px;margin-bottom:4px}.module-launcher small{font-size:9px;color:#81776f;line-height:1.35}
    .photobooth-stage{position:relative;min-height:420px;border:1px solid #cfc3ba;border-radius:18px;overflow:hidden;background:#171514;display:grid;place-items:center}
    .photobooth-stage video,.photobooth-stage canvas,.photobooth-stage img{width:100%;height:100%;max-height:560px;object-fit:cover;display:block}
    .photobooth-stage .photo-empty{color:#ded7d0;text-align:center;font-size:12px;line-height:1.6;padding:24px}.photobooth-stage.flash:after{content:"";position:absolute;inset:0;background:white;animation:boothFlash .35s ease-out both;pointer-events:none}@keyframes boothFlash{0%{opacity:1}100%{opacity:0}}
    .photo-strip{display:grid;grid-template-columns:repeat(4,minmax(80px,1fr));gap:8px;margin-top:12px}.photo-strip figure{margin:0;position:relative;border-radius:12px;overflow:hidden;aspect-ratio:4/3;background:#ddd}.photo-strip img{width:100%;height:100%;object-fit:cover}.photo-strip a{position:absolute;right:6px;bottom:6px;border-radius:999px;background:rgba(20,18,17,.76);color:#fff;text-decoration:none;font:700 8px/1 system-ui;padding:6px 7px}
    .calendar-shell{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(260px,.7fr);gap:14px;margin-top:20px}.calendar-board{border:1px solid #ddd3ca;background:rgba(255,255,255,.58);border-radius:18px;padding:16px}.calendar-toolbar{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:12px}.calendar-toolbar h2{margin:0;font:600 20px Georgia,serif}.calendar-weekdays,.calendar-days{display:grid;grid-template-columns:repeat(7,1fr);gap:5px}.calendar-weekdays span{text-align:center;font:700 8px/1.2 system-ui;text-transform:uppercase;letter-spacing:.08em;color:#8b8179;padding:7px 2px}.calendar-day{position:relative;min-height:88px;border:1px solid #e0d7cf;border-radius:11px;background:rgba(255,255,255,.5);padding:7px;text-align:left;cursor:pointer;color:inherit}.calendar-day.other{opacity:.35}.calendar-day.today{box-shadow:inset 0 0 0 2px rgba(var(--aura-rgb,216,95,109),.55)}.calendar-day.selected{background:rgba(var(--aura-rgb,216,95,109),.12);border-color:rgba(var(--aura-rgb,216,95,109),.55)}.calendar-day-num{font:700 10px system-ui}.calendar-event-chip{display:block;margin-top:5px;padding:4px 5px;border-radius:7px;background:#eee1dc;font:700 8px/1.2 system-ui;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.calendar-mini{margin:10px 0 8px}.calendar-mini-head{display:flex;justify-content:space-between;font:700 9px system-ui;margin-bottom:6px}.calendar-mini-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:3px}.calendar-mini-grid span{display:grid;place-items:center;min-height:22px;border-radius:6px;font:8px system-ui;background:rgba(255,255,255,.45)}.calendar-mini-grid .today{background:rgba(var(--aura-rgb,216,95,109),.18);font-weight:800}
    .dyk-game{display:grid;grid-template-columns:minmax(0,1fr) 250px;gap:14px;margin-top:20px}.dyk-card{min-height:360px;border:1px solid #ddd3ca;background:rgba(255,255,255,.62);border-radius:24px;padding:28px;display:flex;flex-direction:column;justify-content:space-between}.dyk-kicker{font:700 9px system-ui;text-transform:uppercase;letter-spacing:.12em;color:#8b8179}.dyk-question{font:500 clamp(25px,4vw,42px)/1.08 Georgia,serif;margin:16px 0 24px}.dyk-options{display:grid;gap:8px}.dyk-option{border:1px solid #d9d0c7;background:rgba(255,255,255,.72);border-radius:12px;padding:12px 13px;text-align:left;font:600 11px system-ui;cursor:pointer}.dyk-option.correct{background:#edf6ee;border-color:#7ea787}.dyk-option.wrong{background:#f8eaea;border-color:#b98080}.dyk-option:disabled{cursor:default}.dyk-source{margin-top:13px;font-size:9px;line-height:1.5;color:#7b716a}.dyk-source a{color:inherit}.dyk-score{font:500 48px/1 Georgia,serif;margin:10px 0}.dyk-side small{font-size:9px;color:#847a73}
    .module-map{height:520px;border-radius:17px;overflow:hidden;border:1px solid #d6cbc2;background:#ddd}.map-coordinate{font:9px/1.5 ui-monospace,SFMono-Regular,monospace;color:#80756e;margin:7px 0}.map-pin-list{max-height:360px;overflow:auto}.studio-map-card{min-height:170px}.studio-map-visual{height:78px;border:1px solid #d8cec5;border-radius:12px;margin:10px 0;background:radial-gradient(circle at 30% 55%,rgba(var(--aura-rgb,216,95,109),.35) 0 4px,transparent 5px),radial-gradient(circle at 67% 32%,#202020 0 3px,transparent 4px),linear-gradient(35deg,transparent 48%,rgba(80,70,62,.14) 49% 51%,transparent 52%),linear-gradient(125deg,#e9e1d8,#f7f1ea);position:relative;overflow:hidden}.studio-map-visual:before,.studio-map-visual:after{content:"";position:absolute;border:1px solid rgba(90,79,70,.16);border-radius:50%;width:120px;height:90px}.studio-map-visual:before{left:-20px;top:25px}.studio-map-visual:after{right:-26px;top:-30px}
    .closet-connect{display:flex;gap:8px;align-items:center}.closet-connect .module-input{flex:1}.depop-mark{width:40px;height:40px;border-radius:12px;background:#ff3f55;color:#fff;display:grid;place-items:center;font:900 9px system-ui;letter-spacing:.04em}
    .module-chat{height:300px;overflow:auto;display:grid;align-content:start;gap:7px;padding:8px;border:1px solid #ded5cd;border-radius:14px;background:rgba(255,255,255,.36)}.module-bubble{max-width:78%;padding:9px 11px;border-radius:13px;background:#fff;font-size:11px;line-height:1.45}.module-bubble.mine{margin-left:auto;background:#efdad3}
    .module-quiz button{width:100%;text-align:left;margin-top:7px;border:1px solid #d9d0c7;background:rgba(255,255,255,.62);border-radius:11px;padding:10px;font-size:10px;cursor:pointer}.module-quiz button.correct{border-color:#7ea787;background:#edf6ee}.module-quiz button.wrong{border-color:#b98080;background:#f8eaea}
    body.night-mode .module-workspace{background:linear-gradient(180deg,rgba(31,29,28,.97),rgba(25,23,22,.98));color:#f3eee8}.night-mode .module-heading,.night-mode .module-card,.night-mode .module-list-item,.night-mode .module-orbit-row,.night-mode .module-launcher,.night-mode .module-input,.night-mode .module-textarea,.night-mode .module-select,.night-mode .module-chat,.night-mode .calendar-board,.night-mode .calendar-day,.night-mode .dyk-card,.night-mode .dyk-option{border-color:#504943;background:rgba(45,41,39,.78);color:#f4eee8}.night-mode .module-heading p,.night-mode .module-card>p,.night-mode .module-list-item small,.night-mode .module-route,.night-mode .module-status,.night-mode .module-launcher small,.night-mode .dyk-source,.night-mode .dyk-side small{color:#b6aaa2}.night-mode .module-back,.night-mode .module-action.ghost{background:#302c2a;border-color:#514a45;color:#eee7e0}.night-mode .module-bubble{background:#3b3633}.night-mode .module-bubble.mine{background:#5a3d3e}.night-mode .calendar-event-chip{background:#594746}
    @media(max-width:850px){.module-grid,.calendar-shell,.dyk-game{grid-template-columns:1fr}.module-card.wide{grid-column:1}.module-launchers{grid-template-columns:repeat(2,minmax(0,1fr))}.module-form.two,.module-form.three{grid-template-columns:1fr}.module-orbit{grid-template-columns:1fr}.module-heading{grid-template-columns:1fr}.module-badge{justify-self:start}.calendar-day{min-height:68px}.photo-strip{grid-template-columns:repeat(2,1fr)}}
    @media(max-width:560px){.calendar-board{padding:9px}.calendar-days,.calendar-weekdays{gap:2px}.calendar-day{min-height:52px;padding:4px}.calendar-event-chip{font-size:0;width:6px;height:6px;border-radius:50%;padding:0}.module-map{height:420px}}
  `;
  document.head.appendChild(style);

  const workspace = document.createElement('section');
  workspace.id = 'moduleWorkspace';
  workspace.className = 'module-workspace';
  workspace.hidden = true;
  workspace.innerHTML = `<div class="module-shell"><div class="module-top"><button class="module-back" id="moduleBack" type="button">← Studio</button><span class="module-route">BIGLWA / Studio / <b id="moduleRouteName">Module</b></span></div><div id="moduleWorkspaceBody"></div></div>`;
  const footer = $('.site-policy-footer', main);
  if (footer) main.insertBefore(workspace, footer); else main.appendChild(workspace);

  const body = $('#moduleWorkspaceBody');
  const routeName = $('#moduleRouteName');
  const moduleBack = $('#moduleBack');
  const known = new Set(['create','calendar','orbit','feed','connect','camera','diary','stream','library','archive','closet','rooms','room','boards','notes','projects','project','games','learn','didyouknow','map']);
  const labels = {create:'Create',calendar:'Calendar',orbit:'Orbit',feed:'Feed',connect:'Connect',camera:'Photobooth',diary:'Diary',stream:'Stream',library:'Library',archive:'Archive',closet:'Closet',rooms:'The Lounge',room:'The Lounge',boards:'Boards',notes:'Quick Notes',projects:'Projects',project:'Projects',games:'Games',learn:'Did You Know?',didyouknow:'Did You Know?',map:'Map'};
  const desc = {create:'Start something and send it to the right part of BIGLWA.',calendar:'Your actual month view for events and deadlines, with a separate sync path for an outside calendar.',orbit:'Connect the creative platforms that make up your orbit. Keep public profile paths and future login/authorization paths separate.',feed:'Publish a small update to your local Studio feed.',connect:'Find collaborators and keep a small connection list.',camera:'A real browser photobooth: start the camera, pose, capture, retake, and save a frame without uploading it.',diary:'A private writing page that autosaves in this browser.',stream:'Plan a screening, talk, radio set, workshop, or live session.',library:'Build a returnable shelf of texts, PDFs, links, cases, and research.',archive:'Record materials worth preserving with enough context to find them again.',closet:'Draft preloved or creative listings and keep a Depop connection path beside them.',rooms:'A shared-space prototype for conversation and working together.',boards:'Create visual/reference boards with names and context.',notes:'A fast private scratchpad that autosaves.',projects:'Track projects and collaborative work in progress.',games:'Small culture games and learning interactions.',learn:'A playable Did You Know? deck with answers, score, context, and sources.',map:'A shared geography layer for places, memories, projects, and community pins.'};

  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const readJSON = (k, fallback=[]) => { try { return JSON.parse(localStorage.getItem(k) || JSON.stringify(fallback)); } catch { return fallback; } };
  const writeJSON = (k, v) => localStorage.setItem(k, JSON.stringify(v));
  const heading = (key, extra='') => `<div class="module-heading"><div><h1>${esc(labels[key] || key)}</h1><p>${esc(desc[key] || 'A working BIGLWA space.')}${extra ? ` <strong>${esc(extra)}</strong>` : ''}</p></div><span class="module-badge">working page</span></div>`;
  const listHtml = (items, type='item') => items.length ? items.map((x,i)=>`<div class="module-list-item"><div><b>${esc(x.title || x.name || x.text || type)}</b><small>${esc(x.meta || x.detail || x.date || '')}</small></div><button type="button" data-remove-item="${i}" aria-label="Remove">remove</button></div>`).join('') : `<div class="module-status">Nothing saved yet.</div>`;
  const safeOpen = url => { if(!url) return; const target=/^https?:\/\//i.test(url)?url:`https://${url}`; window.open(target,'_blank','noopener'); };

  function renderCollection(key, fields, sample=[]){
    const storage=`biglwaModule_${key}`;
    const items=readJSON(storage,sample);
    const fieldMarkup=fields.map(f=>`<input class="module-input" name="${f.name}" placeholder="${esc(f.placeholder)}" ${f.type?`type="${f.type}"`:''}>`).join('');
    body.innerHTML = heading(key) + `<div class="module-grid"><section class="module-card"><h2>Add</h2><p>Saved locally in this prototype.</p><form class="module-form" id="moduleCollectionForm">${fieldMarkup}<button class="module-action" type="submit">Save</button></form><div class="module-status" id="moduleStatus"></div></section><section class="module-card"><h2>Saved</h2><div class="module-list" id="moduleCollectionList">${listHtml(items,key)}</div></section></div>`;
    const form=$('#moduleCollectionForm',body), list=$('#moduleCollectionList',body), status=$('#moduleStatus',body);
    const render=()=>{const cur=readJSON(storage,[]);list.innerHTML=listHtml(cur,key)};
    form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form);const vals=Object.fromEntries(fd.entries());const title=(vals.title||vals.name||'').trim();if(!title){status.textContent='Give it a name first.';return;}const meta=fields.slice(1).map(f=>vals[f.name]).filter(Boolean).join(' · ');const cur=readJSON(storage,[]);cur.unshift({title,meta,date:new Date().toLocaleDateString()});writeJSON(storage,cur);form.reset();status.textContent='Saved.';status.classList.add('ok');render();});
    list.addEventListener('click',e=>{const b=e.target.closest('[data-remove-item]');if(!b)return;const cur=readJSON(storage,[]);cur.splice(Number(b.dataset.removeItem),1);writeJSON(storage,cur);render();});
  }

  function monthKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
  function dayKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  function calendarGridDate(year,month,index){const first=new Date(year,month,1);return new Date(year,month,1-first.getDay()+index)}
  function miniCalendarMarkup(){
    const now=new Date(), year=now.getFullYear(), month=now.getMonth();
    const cells=Array.from({length:42},(_,i)=>{const d=calendarGridDate(year,month,i),same=d.getMonth()===month,today=dayKey(d)===dayKey(now);return `<span class="${today?'today':''}" style="${same?'':'opacity:.35'}">${d.getDate()}</span>`}).join('');
    return `<div class="calendar-mini"><div class="calendar-mini-head"><span>${now.toLocaleString(undefined,{month:'long'})}</span><span>${year}</span></div><div class="calendar-mini-grid">${cells}</div></div>`;
  }

  function renderCalendar(){
    const storage='biglwaCalendarEvents';
    const syncKey='biglwaCalendarSyncPath';
    let view=readJSON('biglwaCalendarView',null); if(!view||typeof view.year!=='number') view={year:new Date().getFullYear(),month:new Date().getMonth()};
    let selected=localStorage.getItem('biglwaCalendarSelected')||dayKey(new Date());
    const events=()=>readJSON(storage,[]);
    const monthName=()=>new Date(view.year,view.month,1).toLocaleString(undefined,{month:'long',year:'numeric'});
    const draw=()=>{
      const all=events();
      const days=Array.from({length:42},(_,i)=>{
        const d=calendarGridDate(view.year,view.month,i), key=dayKey(d), dayEvents=all.filter(x=>x.date===key), other=d.getMonth()!==view.month, today=key===dayKey(new Date());
        return `<button class="calendar-day ${other?'other':''} ${today?'today':''} ${selected===key?'selected':''}" data-cal-date="${key}" type="button"><span class="calendar-day-num">${d.getDate()}</span>${dayEvents.slice(0,3).map(e=>`<span class="calendar-event-chip">${esc(e.title)}</span>`).join('')}</button>`;
      }).join('');
      const selectedEvents=all.filter(x=>x.date===selected);
      body.innerHTML=heading('calendar')+`<div class="calendar-shell"><section class="calendar-board"><div class="calendar-toolbar"><div class="module-actions" style="margin:0"><button class="module-action ghost" id="calPrev" type="button">←</button><button class="module-action ghost" id="calToday" type="button">Today</button></div><h2>${monthName()}</h2><button class="module-action ghost" id="calNext" type="button">→</button></div><div class="calendar-weekdays">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-days">${days}</div></section><aside class="module-card"><h2>${new Date(selected+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</h2><form class="module-form" id="calendarEventForm"><input class="module-input" name="title" placeholder="Event title" required><input class="module-input" type="time" name="time"><button class="module-action" type="submit">Add event</button></form><div class="module-list" id="calendarSelectedEvents">${listHtml(selectedEvents,'event')}</div><hr style="border:0;border-top:1px solid #ddd3ca;margin:18px 0"><h2>Calendar sync</h2><p>Keep this separate from Orbit. Paste a Google, Apple, Outlook, webcal, or .ics path here.</p><input class="module-input" id="calendarPageSync" value="${esc(localStorage.getItem(syncKey)||'')}" placeholder="webcal://… · calendar URL · .ics"><div class="module-actions"><button class="module-action" id="calendarPageSave" type="button">Save sync path</button></div><div class="module-status" id="calendarSyncPageStatus"></div></aside></div>`;
      $('#calPrev',body).onclick=()=>{view.month--;if(view.month<0){view.month=11;view.year--}writeJSON('biglwaCalendarView',view);draw()};
      $('#calNext',body).onclick=()=>{view.month++;if(view.month>11){view.month=0;view.year++}writeJSON('biglwaCalendarView',view);draw()};
      $('#calToday',body).onclick=()=>{const n=new Date();view={year:n.getFullYear(),month:n.getMonth()};selected=dayKey(n);writeJSON('biglwaCalendarView',view);localStorage.setItem('biglwaCalendarSelected',selected);draw()};
      $$('.calendar-day',body).forEach(btn=>btn.onclick=()=>{selected=btn.dataset.calDate;localStorage.setItem('biglwaCalendarSelected',selected);const d=new Date(selected+'T12:00:00');view={year:d.getFullYear(),month:d.getMonth()};writeJSON('biglwaCalendarView',view);draw()});
      $('#calendarEventForm',body).onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),title=(fd.get('title')||'').trim(),time=fd.get('time')||'';if(!title)return;const cur=events();cur.push({title,date:selected,meta:[selected,time].filter(Boolean).join(' · '),time});writeJSON(storage,cur);draw()};
      $('#calendarSelectedEvents',body).onclick=e=>{const b=e.target.closest('[data-remove-item]');if(!b)return;const dayItems=events().filter(x=>x.date===selected),target=dayItems[Number(b.dataset.removeItem)];if(!target)return;const cur=events();const idx=cur.findIndex(x=>x===target||(x.title===target.title&&x.date===target.date&&x.time===target.time));if(idx>=0)cur.splice(idx,1);writeJSON(storage,cur);draw()};
      $('#calendarPageSave',body).onclick=()=>{const v=$('#calendarPageSync',body).value.trim();localStorage.setItem(syncKey,v);$('#calendarSyncPageStatus',body).textContent=v?'Sync path saved.':'Sync path cleared.';$('#calendarSyncPageStatus',body).classList.add('ok')};
    };
    draw();
  }

  function renderOrbitPage(){
    const apps=[['instagram','IG','Instagram'],['facebook','FB','Facebook'],['tiktok','TT','TikTok'],['pinterest','P','Pinterest'],['spotify','SP','Spotify'],['soundcloud','SC','SoundCloud'],['youtube','YT','YouTube'],['drive','GD','Google Drive'],['calendar','GC','Google Calendar']];
    const links=readJSON('biglwaOrbitLinks',{}), auth=readJSON('biglwaOrbitAuthPaths',{});
    body.innerHTML=heading('orbit')+`<div class="module-grid"><section class="module-card wide"><h2>Your orbit</h2><p>These are the creative-network paths we actually need here. Calendar syncing lives in Calendar, not Orbit. Profile and login/authorization paths remain separate so we can wire real OAuth later.</p><div class="module-orbit">${apps.map(([k,g,n])=>`<div class="module-orbit-row"><header><b>${n}</b><span>${g}</span></header><label class="orbit-field-label">Public profile / page</label><input class="module-input" data-orbit-path="${k}" value="${esc(links[k]||'')}" placeholder="Paste profile URL"><label class="orbit-field-label">Future login / authorization path</label><input class="module-input" data-orbit-auth="${k}" value="${esc(auth[k]||'')}" placeholder="OAuth, login, or developer callback path"><div class="module-actions"><button class="module-action" type="button" data-orbit-save="${k}">Save</button><button class="module-action ghost" type="button" data-orbit-open="${k}" ${links[k]?'':'disabled'}>Open profile</button></div></div>`).join('')}</div><div class="module-status" id="orbitPageStatus"></div></section></div>`;
    body.onclick=e=>{const save=e.target.closest('[data-orbit-save]'),open=e.target.closest('[data-orbit-open]');if(save){const k=save.dataset.orbitSave,p=$(`[data-orbit-path="${k}"]`,body).value.trim(),a=$(`[data-orbit-auth="${k}"]`,body).value.trim(),all=readJSON('biglwaOrbitLinks',{}),auths=readJSON('biglwaOrbitAuthPaths',{});p?all[k]=p:delete all[k];a?auths[k]=a:delete auths[k];writeJSON('biglwaOrbitLinks',all);writeJSON('biglwaOrbitAuthPaths',auths);$('#orbitPageStatus',body).textContent=`${apps.find(x=>x[0]===k)?.[2]||'Orbit'} paths saved.`;$('#orbitPageStatus',body).classList.add('ok');}if(open){safeOpen(readJSON('biglwaOrbitLinks',{})[open.dataset.orbitOpen]);}};
  }

  function renderWriting(key){
    const storage=`biglwaDraft_${key}`;
    body.innerHTML=heading(key)+`<div class="module-grid"><section class="module-card wide"><h2>${key==='diary'?'New diary page':'Scratchpad'}</h2><textarea class="module-textarea" id="moduleWritingArea" placeholder="Write here…">${esc(localStorage.getItem(storage)||'')}</textarea><div class="module-status" id="moduleWritingStatus">Private to this browser · autosaves</div></section></div>`;
    const area=$('#moduleWritingArea',body),status=$('#moduleWritingStatus',body);let t;area.addEventListener('input',()=>{status.textContent='Saving…';clearTimeout(t);t=setTimeout(()=>{localStorage.setItem(storage,area.value);status.textContent='Saved locally.';status.classList.add('ok');},250)});
  }

  function renderFeed(){
    const storage='biglwaFeedPosts'; const seed=[{title:'Maya added to Diaspora Docs',meta:'project update'},{title:'Jules published a closet drop',meta:'community'}]; const posts=readJSON(storage,seed);
    body.innerHTML=heading('feed')+`<div class="module-grid"><section class="module-card"><h2>Post an update</h2><form class="module-form" id="feedComposer"><textarea class="module-input" style="min-height:96px;resize:vertical" name="text" placeholder="What changed? What are you making?"></textarea><button class="module-action" type="submit">Post</button></form></section><section class="module-card"><h2>Collective feed</h2><div class="module-list" id="feedPageList">${listHtml(posts,'post')}</div></section></div>`;
    const render=()=>{$('#feedPageList',body).innerHTML=listHtml(readJSON(storage,[]),'post')}; $('#feedComposer',body).onsubmit=e=>{e.preventDefault();const text=(new FormData(e.currentTarget).get('text')||'').trim();if(!text)return;const cur=readJSON(storage,[]);cur.unshift({title:text,meta:'just now · local prototype'});writeJSON(storage,cur);e.currentTarget.reset();render()}; $('#feedPageList',body).onclick=e=>{const b=e.target.closest('[data-remove-item]');if(!b)return;const cur=readJSON(storage,[]);cur.splice(Number(b.dataset.removeItem),1);writeJSON(storage,cur);render()};
  }

  function renderConnect(){
    const people=[['Sam','film · LA'],['Noor','law · NYC'],['Ty','design · ATL'],['Imani','research · DC'],['Mika','music · Chicago'],['Ari','archives · LA']]; const connected=new Set(readJSON('biglwaConnections',[]));
    body.innerHTML=heading('connect')+`<div class="module-grid"><section class="module-card wide"><h2>Find people</h2><input class="module-input" id="connectSearch" placeholder="Search skill, name, or city"><div class="module-list" id="connectPageList"></div></section></div>`;
    const render=(q='')=>{const list=$('#connectPageList',body);list.innerHTML=people.filter(p=>p.join(' ').toLowerCase().includes(q.toLowerCase())).map(([name,meta])=>`<div class="module-list-item"><div><b>${name}</b><small>${meta}</small></div><button type="button" data-connect="${name}">${connected.has(name)?'connected':'connect'}</button></div>`).join('')};render(); $('#connectSearch',body).oninput=e=>render(e.target.value); $('#connectPageList',body).onclick=e=>{const b=e.target.closest('[data-connect]');if(!b)return;connected.has(b.dataset.connect)?connected.delete(b.dataset.connect):connected.add(b.dataset.connect);writeJSON('biglwaConnections',[...connected]);render($('#connectSearch',body).value)};
  }

  let activeCameraStream=null;
  function stopCamera(){if(activeCameraStream){activeCameraStream.getTracks().forEach(t=>t.stop());activeCameraStream=null}}
  function renderCamera(){
    stopCamera();
    body.innerHTML=heading('camera')+`<div class="module-grid"><section class="module-card wide"><h2>Photobooth</h2><p>Your camera feed stays in the browser. Nothing is uploaded by starting the booth or taking a frame.</p><div class="photobooth-stage" id="photoStage"><div class="photo-empty"><b>Camera is off.</b><br>Start the booth when you're ready.</div></div><div class="module-actions"><button class="module-action" id="photoStart" type="button">Start camera</button><button class="module-action secondary" id="photoCapture" type="button" disabled>Capture</button><button class="module-action ghost" id="photoFlip" type="button" disabled>Flip camera</button><label class="module-action ghost">Use existing photo<input id="cameraFile" type="file" accept="image/*" hidden></label></div><div class="photo-strip" id="photoStrip"></div><div class="module-status" id="photoStatus">Camera permission is requested only when you press Start camera.</div></section></div>`;
    const stage=$('#photoStage',body),cap=$('#photoCapture',body),flip=$('#photoFlip',body),status=$('#photoStatus',body),strip=$('#photoStrip',body);let facing='user';
    const start=async()=>{try{stopCamera();activeCameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:facing},audio:false});stage.innerHTML='<video id="boothVideo" autoplay playsinline muted></video>';$('#boothVideo',body).srcObject=activeCameraStream;cap.disabled=false;flip.disabled=false;status.textContent='Photobooth ready.';status.classList.add('ok')}catch(err){status.textContent='Camera could not start. Check browser camera permission or use an existing photo.'}};
    $('#photoStart',body).onclick=start; $('#photoFlip',body).onclick=async()=>{facing=facing==='user'?'environment':'user';await start()};
    cap.onclick=()=>{const v=$('#boothVideo',body);if(!v||!v.videoWidth)return;stage.classList.add('flash');setTimeout(()=>stage.classList.remove('flash'),380);const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0,c.width,c.height);const url=c.toDataURL('image/jpeg',.9);const fig=document.createElement('figure');fig.innerHTML=`<img src="${url}" alt="Photobooth capture"><a href="${url}" download="biglwa-photobooth-${Date.now()}.jpg">save</a>`;strip.prepend(fig);status.textContent='Captured. Save it if you want to keep it.'};
    $('#cameraFile',body).onchange=e=>{const f=e.target.files?.[0];if(!f)return;const url=URL.createObjectURL(f);stage.innerHTML=`<img src="${url}" alt="Selected photo">`;cap.disabled=true;status.textContent='Local photo preview — nothing uploaded.'};
  }

  function renderRoom(){
    const storage='biglwaRoomMessages',messages=readJSON(storage,[{text:'Welcome to the Lounge.',mine:false}]); body.innerHTML=heading('rooms')+`<div class="module-grid"><section class="module-card wide"><h2>The Lounge</h2><div class="module-chat" id="roomChat">${messages.map(m=>`<div class="module-bubble ${m.mine?'mine':''}">${esc(m.text)}</div>`).join('')}</div><form class="module-form two" id="roomForm" style="margin-top:8px"><input class="module-input" name="text" placeholder="Say something…"><button class="module-action" type="submit">Send</button></form><div class="module-status">Local prototype — real room sync comes with the backend.</div></section></div>`; $('#roomForm',body).onsubmit=e=>{e.preventDefault();const text=(new FormData(e.currentTarget).get('text')||'').trim();if(!text)return;const cur=readJSON(storage,[]);cur.push({text,mine:true});writeJSON(storage,cur);openModule('rooms','',false)};
  }

  function renderGames(){
    body.innerHTML=heading('games')+`<div class="module-grid"><section class="module-card module-quiz"><h2>Culture check</h2><p>Where did hip-hop emerge as a culture in the 1970s?</p><button data-answer="wrong">Brooklyn</button><button data-answer="correct">The Bronx</button><button data-answer="wrong">Harlem</button><div class="module-status" id="moduleQuizStatus"></div></section><section class="module-card"><h2>More games</h2><p>Did You Know? is its own playable knowledge deck now.</p><button class="module-action" type="button" id="openDYK">Play Did You Know?</button></section></div>`;
    $$('.module-quiz [data-answer]',body).forEach(btn=>btn.onclick=()=>{$$('.module-quiz [data-answer]',body).forEach(x=>x.classList.remove('correct','wrong'));const ok=btn.dataset.answer==='correct';btn.classList.add(ok?'correct':'wrong');$('#moduleQuizStatus',body).textContent=ok?'Correct — the Bronx, New York City.':'Not quite — try again.'}); $('#openDYK',body).onclick=()=>openModule('learn');
  }

  const dykQuestions=[
    {q:'Which borough is widely recognized as the birthplace of hip-hop culture in the 1970s?',a:['The Bronx','Queens','Brooklyn','Manhattan'],correct:0,context:'Hip-hop developed through block parties, DJs, MCs, breaking, and graffiti culture in the Bronx during the 1970s.',source:'Smithsonian — Hip-Hop History',url:'https://nmaahc.si.edu/explore/stories/hip-hop-history'},
    {q:'The Haitian Revolution began in which year?',a:['1776','1789','1791','1804'],correct:2,context:'The uprising that began in 1791 became the Haitian Revolution; Haiti declared independence in 1804.',source:'Encyclopaedia Britannica — Haitian Revolution',url:'https://www.britannica.com/topic/Haitian-Revolution'},
    {q:'In ballroom culture, what is a “house” best understood as?',a:['Only a venue','A chosen-family and competitive collective','A record label','A dance step'],correct:1,context:'Houses have functioned as chosen families, support systems, and competitive units within ballroom communities.',source:'National Museum of African American History and Culture — Ballroom',url:'https://nmaahc.si.edu/'},
    {q:'Which practice best helps an archive preserve meaning rather than just objects?',a:['Removing dates','Keeping provenance and context','Sorting only by popularity','Deleting conflicting accounts'],correct:1,context:'Provenance, source information, dates, and surrounding context help future readers understand what an object meant and where it came from.',source:'Society of American Archivists — archival principles',url:'https://www2.archivists.org/'}
  ];
  function renderLearn(){
    let index=Number(localStorage.getItem('biglwaDYKIndex')||0)%dykQuestions.length;let score=Number(localStorage.getItem('biglwaDYKScore')||0);let answered=false;
    const draw=()=>{const item=dykQuestions[index];body.innerHTML=heading('learn')+`<div class="dyk-game"><section class="dyk-card"><div><span class="dyk-kicker">Card ${index+1} of ${dykQuestions.length}</span><div class="dyk-question">${esc(item.q)}</div><div class="dyk-options">${item.a.map((x,i)=>`<button class="dyk-option" type="button" data-dyk-answer="${i}">${esc(x)}</button>`).join('')}</div><div class="dyk-source" id="dykContext">Choose an answer to reveal the context and source.</div></div><div class="module-actions"><button class="module-action" id="dykNext" type="button" disabled>Next card →</button><button class="module-action ghost" id="dykReset" type="button">Reset score</button></div></section><aside class="module-card dyk-side"><h2>Score</h2><div class="dyk-score">${score}</div><small>Correct answers in this run. This is meant to teach, not punish a wrong guess.</small></aside></div>`;
      $$('.dyk-option',body).forEach(btn=>btn.onclick=()=>{if(answered)return;answered=true;const choice=Number(btn.dataset.dykAnswer),ok=choice===item.correct;$$('.dyk-option',body).forEach((b,i)=>{b.disabled=true;if(i===item.correct)b.classList.add('correct')});if(!ok)btn.classList.add('wrong');if(ok){score++;localStorage.setItem('biglwaDYKScore',score)}$('#dykContext',body).innerHTML=`${esc(item.context)} <a href="${item.url}" target="_blank" rel="noopener">${esc(item.source)} ↗</a>`;$('#dykNext',body).disabled=false;$('.dyk-score',body).textContent=score});
      $('#dykNext',body).onclick=()=>{index=(index+1)%dykQuestions.length;localStorage.setItem('biglwaDYKIndex',index);answered=false;draw()}; $('#dykReset',body).onclick=()=>{score=0;localStorage.setItem('biglwaDYKScore','0');answered=false;draw()};
    };draw();
  }

  function renderCloset(){
    const storage='biglwaModule_closet',depopKey='biglwaDepopPath';const items=readJSON(storage,[]),depop=localStorage.getItem(depopKey)||'';
    body.innerHTML=heading('closet')+`<div class="module-grid"><section class="module-card"><h2>Depop connection</h2><p>Keep a store/profile path here now; we can wire a real connection/import flow later.</p><div class="closet-connect"><span class="depop-mark">DEPOP</span><input class="module-input" id="depopPath" value="${esc(depop)}" placeholder="https://depop.com/yourshop"></div><div class="module-actions"><button class="module-action" id="saveDepop" type="button">Save path</button><button class="module-action ghost" id="openDepop" type="button" ${depop?'':'disabled'}>Open Depop</button></div><div class="module-status" id="depopStatus"></div></section><section class="module-card"><h2>Add closet item</h2><form class="module-form" id="closetForm"><input class="module-input" name="title" placeholder="Item name" required><div class="module-form two"><input class="module-input" name="price" placeholder="Price"><input class="module-input" name="size" placeholder="Size"></div><input class="module-input" name="condition" placeholder="Condition / notes"><input class="module-input" name="link" placeholder="Optional listing link"><button class="module-action" type="submit">Save item</button></form></section><section class="module-card wide"><h2>Your closet</h2><div class="module-list" id="closetList">${listHtml(items,'item')}</div></section></div>`;
    const render=()=>{$('#closetList',body).innerHTML=listHtml(readJSON(storage,[]),'item')};$('#saveDepop',body).onclick=()=>{const v=$('#depopPath',body).value.trim();localStorage.setItem(depopKey,v);$('#depopStatus',body).textContent=v?'Depop path saved.':'Depop path cleared.';$('#openDepop',body).disabled=!v};$('#openDepop',body).onclick=()=>safeOpen(localStorage.getItem(depopKey)||'');$('#closetForm',body).onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),title=(fd.get('title')||'').trim();if(!title)return;const meta=[fd.get('price'),fd.get('size'),fd.get('condition'),fd.get('link')].filter(Boolean).join(' · ');const cur=readJSON(storage,[]);cur.unshift({title,meta});writeJSON(storage,cur);e.currentTarget.reset();render()};$('#closetList',body).onclick=e=>{const b=e.target.closest('[data-remove-item]');if(!b)return;const cur=readJSON(storage,[]);cur.splice(Number(b.dataset.removeItem),1);writeJSON(storage,cur);render()};
  }

  function loadLeaflet(){
    if(window.L)return Promise.resolve();return new Promise((resolve,reject)=>{if(!document.querySelector('link[data-biglwa-leaflet]')){const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.dataset.biglwaLeaflet='1';document.head.appendChild(l)}const existing=document.querySelector('script[data-biglwa-leaflet]');if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.dataset.biglwaLeaflet='1';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});
  }
  let activeMap=null;
  function renderMap(){
    body.innerHTML=heading('map')+`<div class="module-grid"><section class="module-card wide"><div id="biglwaMap" class="module-map"></div><div class="module-status" id="mapStatus">Click anywhere on the map to stage a pin.</div></section><section class="module-card"><h2>Add pin</h2><p>Click a location first, then give it a label and context.</p><div class="map-coordinate" id="mapCoordinate">No location selected.</div><form class="module-form" id="mapPinForm"><input class="module-input" name="title" placeholder="Pin label" required><input class="module-input" name="detail" placeholder="Context, memory, project, venue…"><button class="module-action" id="mapSavePin" type="submit" disabled>Save pin</button></form><div class="module-actions"><button class="module-action ghost" id="mapMyLocation" type="button">Use my location</button></div></section><section class="module-card"><h2>Saved pins</h2><div class="module-list map-pin-list" id="mapPinList"></div></section></div>`;
    let staged=null;const storage='biglwaMapPins';const list=$('#mapPinList',body);const renderList=()=>{const pins=readJSON(storage,[]);list.innerHTML=pins.length?pins.map((p,i)=>`<div class="module-list-item"><div><b>${esc(p.title)}</b><small>${esc(p.detail||'')} · ${Number(p.lat).toFixed(4)}, ${Number(p.lng).toFixed(4)}</small></div><button type="button" data-map-pin="${i}">remove</button></div>`).join(''):'<div class="module-status">No pins yet.</div>'};renderList();
    loadLeaflet().then(()=>{if(activeMap){try{activeMap.remove()}catch{}}activeMap=L.map('biglwaMap',{worldCopyJump:true}).setView([20,0],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(activeMap);const pins=readJSON(storage,[]);pins.forEach(p=>L.marker([p.lat,p.lng]).addTo(activeMap).bindPopup(`<b>${esc(p.title)}</b><br>${esc(p.detail||'')}`));let preview=null;const stage=(lat,lng)=>{staged={lat,lng};if(preview)preview.setLatLng([lat,lng]);else preview=L.marker([lat,lng],{opacity:.65}).addTo(activeMap);$('#mapCoordinate',body).textContent=`${lat.toFixed(5)}, ${lng.toFixed(5)}`;$('#mapSavePin',body).disabled=false};activeMap.on('click',e=>stage(e.latlng.lat,e.latlng.lng));$('#mapMyLocation',body).onclick=()=>{if(!navigator.geolocation){$('#mapStatus',body).textContent='Location is not available in this browser.';return}navigator.geolocation.getCurrentPosition(pos=>{const {latitude,longitude}=pos.coords;activeMap.setView([latitude,longitude],13);stage(latitude,longitude)},()=>{$('#mapStatus',body).textContent='Location permission was not granted.'})};$('#mapPinForm',body).onsubmit=e=>{e.preventDefault();if(!staged)return;const fd=new FormData(e.currentTarget),title=(fd.get('title')||'').trim(),detail=(fd.get('detail')||'').trim();if(!title)return;const cur=readJSON(storage,[]);cur.unshift({title,detail,...staged});writeJSON(storage,cur);L.marker([staged.lat,staged.lng]).addTo(activeMap).bindPopup(`<b>${esc(title)}</b><br>${esc(detail)}`).openPopup();e.currentTarget.reset();staged=null;if(preview){preview.remove();preview=null}$('#mapCoordinate',body).textContent='No location selected.';$('#mapSavePin',body).disabled=true;renderList();enhanceStudioCards()};list.onclick=e=>{const b=e.target.closest('[data-map-pin]');if(!b)return;const cur=readJSON(storage,[]);cur.splice(Number(b.dataset.mapPin),1);writeJSON(storage,cur);renderMap()}}).catch(()=>{$('#mapStatus',body).textContent='The map library could not load. Refresh and try again.'});
  }

  function renderCreate(){const mods=['calendar','feed','projects','camera','diary','boards','closet','archive','stream','map','orbit'];body.innerHTML=heading('create')+`<div class="module-grid"><section class="module-card wide"><h2>Choose where this belongs</h2><div class="module-launchers">${mods.map(k=>`<button class="module-launcher" type="button" data-module-launch="${k}"><b>${labels[k]}</b><small>${desc[k]}</small></button>`).join('')}</div></section></div>`;body.onclick=e=>{const b=e.target.closest('[data-module-launch]');if(b)openModule(b.dataset.moduleLaunch)}};

  function openModule(rawKey, context='', push=true){
    stopCamera();let key=(rawKey||'').toLowerCase();if(key==='room')key='rooms';if(key==='project')key='projects';if(key==='didyouknow')key='learn';if(!known.has(key))key='create';main.classList.add('module-view');workspace.hidden=false;routeName.textContent=labels[key]||key;
    if(key==='calendar')renderCalendar();else if(key==='orbit')renderOrbitPage();else if(key==='diary'||key==='notes')renderWriting(key);else if(key==='feed')renderFeed();else if(key==='connect')renderConnect();else if(key==='camera')renderCamera();else if(key==='rooms')renderRoom();else if(key==='games')renderGames();else if(key==='learn')renderLearn();else if(key==='closet')renderCloset();else if(key==='map')renderMap();else if(key==='create')renderCreate();else if(key==='library')renderCollection('library',[{name:'title',placeholder:'Resource title'},{name:'detail',placeholder:'URL, author, or collection'}],[{title:'Black Visual Culture',meta:'reading shelf'},{title:'Law + Creative Rights',meta:'guides · cases'}]);else if(key==='archive')renderCollection('archive',[{name:'title',placeholder:'Archive entry'},{name:'detail',placeholder:'Context, source, date, or medium'}],[{title:'Community flyer collection',meta:'ephemera · context preserved'}]);else if(key==='boards')renderCollection('boards',[{name:'title',placeholder:'Board name'},{name:'detail',placeholder:'What belongs here?'}],[{title:'My Inspiration',meta:'visual references'}]);else if(key==='projects')renderCollection('projects',[{name:'title',placeholder:'Project name'},{name:'detail',placeholder:'Status · collaborators · next step'}],[{title:'City Screens',meta:'community · 12 collaborators'},{title:'Diaspora Docs',meta:'video · 8 collaborators'}]);else if(key==='stream')renderCollection('stream',[{name:'title',placeholder:'Broadcast title'},{name:'detail',placeholder:'Date · time · format'}]);window.scrollTo({top:0,behavior:'instant'});if(push){try{history.pushState({biglwaModule:key},'',`/studio?view=${encodeURIComponent(key)}`)}catch{}}
  }
  window.openBIGLWAModule=openModule;

  function closeModule(push=true){stopCamera();if(activeMap){try{activeMap.remove()}catch{}activeMap=null}main.classList.remove('module-view');workspace.hidden=true;body.innerHTML='';routeName.textContent='Module';if(push){try{history.pushState({},'', '/studio')}catch{}}}
  moduleBack.addEventListener('click',()=>closeModule());

  function enhanceStudioCards(){
    const cal=$('#calendar');if(cal&&!cal.querySelector('.calendar-mini')){const anchor=cal.querySelector('.arrow-btn')||cal.lastElementChild;const wrap=document.createElement('div');wrap.innerHTML=miniCalendarMarkup();const mini=wrap.firstElementChild;anchor&&anchor.parentNode===cal?cal.insertBefore(mini,anchor):cal.appendChild(mini)}
    const masonry=$('.masonry');if(masonry&&!$('#map')){const games=$('#games');const card=document.createElement('article');card.id='map';card.className='card studio-map-card';card.innerHTML=`<div class="card-head"><span class="eyebrow">Map</span><button class="arrow-btn" type="button" data-open="map" aria-label="Open map">→</button></div><h2 style="font-family:Georgia,serif;margin:8px 0 4px">Map</h2><div class="studio-map-visual" aria-hidden="true"></div><small>${readJSON('biglwaMapPins',[]).length} saved pin${readJSON('biglwaMapPins',[]).length===1?'':'s'} · click to map projects, places, and memories</small>`;games?masonry.insertBefore(card,games):masonry.appendChild(card)}else if($('#map')){const small=$('#map small');if(small)small.textContent=`${readJSON('biglwaMapPins',[]).length} saved pin${readJSON('biglwaMapPins',[]).length===1?'':'s'} · click to map projects, places, and memories`}
  }
  setTimeout(enhanceStudioCards,80);

  document.addEventListener('click',e=>{if(e.target.closest('#moduleWorkspace'))return;const mobile=e.target.closest('#mobileCreate');const trigger=e.target.closest('[data-open],.arrow-btn');if(!mobile&&!trigger)return;let key=mobile?'create':trigger.dataset.open;const card=trigger?.closest('.card');const cardKey=card?.id;if(!known.has(String(key||'').toLowerCase())&&cardKey)key=cardKey;if(!key&&cardKey)key=cardKey;if(!key)return;e.preventDefault();e.stopImmediatePropagation();openModule(key,trigger?.dataset.open||'')},true);
  window.addEventListener('popstate',()=>{const v=new URLSearchParams(location.search).get('view');if(v)openModule(v,'',false);else closeModule(false)});
  const initialView=new URLSearchParams(location.search).get('view');if(initialView)setTimeout(()=>openModule(initialView,'',false),80);
})();
